# Generated by Django 5.1.2 on 2024-11-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_platform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='licence',
            field=models.FileField(blank=True, null=True, upload_to='licences/', verbose_name='Licence (si docteur)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='speciality',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Spécialité médicale'),
        ),
    ]
